# Generated by Django 5.2 on 2025-04-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawApp.category'),
        ),
    ]
