# Generated by Django 5.2 on 2025-04-25 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawApp', '0002_artwork_likes_alter_artwork_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='likes',
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
