# Generated by Django 5.2 on 2025-04-25 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawApp', '0003_remove_artwork_likes_artwork_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
