# Generated by Django 5.2 on 2025-05-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawApp', '0007_artwork_status_alter_artwork_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='custom_categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rawApp.artist', verbose_name='Художник'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='custom_artist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя художника (если нет в списке)'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
