# Generated by Django 5.2 on 2025-05-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawApp', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
